# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'sdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sdkDemo
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'GoogleMLKit/TextRecognition', '2.2.0'
    pod 'GoogleMLKit/FaceDetection'
    pod 'KDCircularProgress'
end
